// Code generated by catalog/enrol; DO NOT EDIT.

// Package registry enrols every shipped rule: importing it registers each sin, skill and detector.
package registry

import (
	_ "github.com/jessegall/code-commandments/detectors/backend"
	_ "github.com/jessegall/code-commandments/detectors/backend/concurrent"
	_ "github.com/jessegall/code-commandments/detectors/backend/phptypes"
	_ "github.com/jessegall/code-commandments/detectors/backend/spatie"
	_ "github.com/jessegall/code-commandments/detectors/frontend"
	_ "github.com/jessegall/code-commandments/detectors/python"
	_ "github.com/jessegall/code-commandments/detectors/typescript"
	_ "github.com/jessegall/code-commandments/published/spatie"
	_ "github.com/jessegall/code-commandments/sins/backend"
	_ "github.com/jessegall/code-commandments/sins/backend/concurrent"
	_ "github.com/jessegall/code-commandments/sins/backend/laravel"
	_ "github.com/jessegall/code-commandments/sins/backend/phptypes"
	_ "github.com/jessegall/code-commandments/sins/backend/spatie"
	_ "github.com/jessegall/code-commandments/sins/frontend"
	_ "github.com/jessegall/code-commandments/sins/python"
	_ "github.com/jessegall/code-commandments/sins/typescript"
	_ "github.com/jessegall/code-commandments/skill/backend"
	_ "github.com/jessegall/code-commandments/skill/backend/concurrent"
	_ "github.com/jessegall/code-commandments/skill/backend/laravel"
	_ "github.com/jessegall/code-commandments/skill/backend/spatie"
	_ "github.com/jessegall/code-commandments/skill/frontend"
	_ "github.com/jessegall/code-commandments/skill/python"
	_ "github.com/jessegall/code-commandments/skill/typescript"
)
