// Code generated by catalog/enrol; DO NOT EDIT.

// Package registry enrols every shipped rule: importing it registers each sin, skill and detector.
package registry

import (
	_ "github.com/jessegall/code-commandments/detectors/frontend"
	_ "github.com/jessegall/code-commandments/detectors/python"
	_ "github.com/jessegall/code-commandments/detectors/typescript"
	_ "github.com/jessegall/code-commandments/published/spatie"
	_ "github.com/jessegall/code-commandments/sins/csharp"
	_ "github.com/jessegall/code-commandments/sins/frontend"
	_ "github.com/jessegall/code-commandments/sins/python"
	_ "github.com/jessegall/code-commandments/sins/typescript"
	_ "github.com/jessegall/code-commandments/skill/csharp"
	_ "github.com/jessegall/code-commandments/skill/frontend"
	_ "github.com/jessegall/code-commandments/skill/python"
	_ "github.com/jessegall/code-commandments/skill/typescript"
)
