// Code generated by catalog/enrol; DO NOT EDIT.

// Package registry enrols every shipped rule: importing it registers each sin, skill and detector.
package registry

import (
	_ "github.com/jessegall/code-commandments/sins/backend"
	_ "github.com/jessegall/code-commandments/sins/backend/concurrent"
	_ "github.com/jessegall/code-commandments/sins/backend/laravel"
	_ "github.com/jessegall/code-commandments/sins/backend/phptypes"
	_ "github.com/jessegall/code-commandments/sins/backend/spatie"
	_ "github.com/jessegall/code-commandments/skill/backend"
	_ "github.com/jessegall/code-commandments/skill/backend/concurrent"
	_ "github.com/jessegall/code-commandments/skill/backend/laravel"
	_ "github.com/jessegall/code-commandments/skill/backend/spatie"
)
