<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Strategies;

/**
 * First non-null result wins — the chain stops at the first entry that
 * resolves. Returns null when nothing matches.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 */
final class FirstResultWins implements ResolveStrategy
{

    private function __construct() {}

    public static function make(): self
    {
        /** @var self|null $instance */
        static $instance = null;

        return $instance ??= new self();
    }

    public function __invoke(iterable $resolvers, mixed $input): mixed
    {
        foreach ($resolvers as $resolve)
        {
            $result = $resolve($input);

            if ($result !== null)
            {
                return $result;
            }
        }

        return null;
    }

}
