<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Predicates;

/**
 * True when the value is an instance of the given class or interface.
 *
 *     HasClass::of(BagSocket::class)->when(...)
 *
 * Use this when you dispatch on what an object *is* (its runtime type).
 * To compare an enum/scalar tag by value, use Equals::to(...) instead —
 * there the matched thing is the input and the class is only the result.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @template T of object
 *
 * @extends Predicate<T>
 */
final class HasClass extends Predicate
{

    /**
     * @param class-string<T> $class
     */
    private function __construct(
        private readonly string $class,
    ) {}

    /**
     * @template TObject of object
     * @param class-string<TObject> $class
     * @return self<TObject>
     */
    public static function of(string $class): self
    {
        return new self($class);
    }

    public function __invoke(mixed $value): bool
    {
        return $value instanceof $this->class;
    }

}
