<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Predicates;

/**
 * A resolver chain entry under construction: a Predicate plus a transform
 * applied to the matched input before the factory. Built by
 * {@see Predicate::transform()}; call {@see self::then()} with the factory.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @template TMid
 */
final class PredicateEntry
{

    private readonly \Closure $transform;

    /**
     * @param  Predicate<mixed>  $predicate
     * @param  callable(mixed): TMid  $transform
     */
    public function __construct(
        private readonly Predicate $predicate,
        callable $transform,
    ) {
        $this->transform = $transform(...);
    }

    /**
     * Match, transform, THEN produce. $make is either a FACTORY callable (it
     * receives the transformed value) or a BARE VALUE (a scalar/enum/constant
     * returned as-is, no closure wrapper). Only genuine callables (Closures,
     * [obj, method], invokables) are called; a string/scalar is the value
     * itself.
     *
     * @template TOut
     * @param  (callable(TMid): TOut)|TOut  $make
     * @return callable(mixed): (TOut|null)
     */
    public function then(mixed $make): callable
    {
        return fn (mixed $value): mixed => ($this->predicate)($value)
            ? ($make instanceof \Closure || (! \is_string($make) && \is_callable($make)) ? $make(($this->transform)($value)) : $make)
            : null;
    }

}
