package engine_test

import (
	"encoding/json"
	"fmt"
	"testing"

	"github.com/jessegall/code-commandments/engine"
)

// Each case's verdict is PHP's Frozen::isFrozenFile's for the same path and source.
func TestAFileOutsidePHPIsFrozenAsThePHPToolReadsIt(t *testing.T) {
	cases := []struct {
		path, source string
		frozen       bool
	}{
		{"/p/a.py", "x = 1  # @frozen\n", false},
		{"/p/a.py", "  # @frozen\nx = 1\n", true},
		{"/p/a.vue", "<template>\n  <!-- @frozen -->\n</template>\n", true},
		{"/p/a.vue", "<script>\n// @frozen\n</script>\n", false},
		{"/p/a.ts", " * @frozen\n", true},
		{"/p/A.Designer.cs", "class A {}\n", true},
		{"/p/A.cs", "\xef\xbb\xbf// <auto-generated>\n\nclass A {}\n", true},
		{"/p/A.cs", "class A {}\n// <auto-generated>\n", false},
	}
	for _, c := range cases {
		codebase, err := engine.FromString(streamOf(c.path, c.source), map[string]string{c.path: c.source})
		if err != nil {
			t.Fatal(err)
		}
		if got := codebase.Files()[0].IsFrozen(); got != c.frozen {
			t.Errorf("%s %q: got %v, want %v", c.path, c.source, got, c.frozen)
		}
	}
}

// streamOf is a stream holding one file with no nodes under its root: the verdict reads only its path and text.
func streamOf(path, source string) string {
	quoted, _ := json.Marshal(path)

	return fmt.Sprintf(`{"header": {"contract": "tree", "version": 1, "language": "python", "bridge": {"name": "test", "version": "1"}, "roots": ["/p"]}}
{"file": {"path": %s, "language": "python", "errors": 0, "root": {"id": 0, "kind": "File", "role": "other", "span": [0, %d, 1]}, "comments": []}}
{"trailer": {"files": 1}}
`, quoted, len(source))
}
