package engine

import (
	"path/filepath"
	"regexp"
	"strings"

	"github.com/jessegall/code-commandments/contract"
)

// The stamps that freeze a file: one `commandments freeze` writes, and one a generator puts on a file it regenerates.
const (
	FrozenMarker    = "@code-commandments-frozen"
	GeneratedMarker = "@code-commandments-generated"
)

var frozenTag = regexp.MustCompile(`(?i)@frozen\b`)

// Freezer says whether a file's own syntax declares it frozen, beyond a comment that says so.
type Freezer func(*File) bool

var freezers = map[contract.Language]Freezer{}

// Freezes enrols the freezer of one language, from that language's own package.
func Freezes(language contract.Language, freezer Freezer) {
	freezers[language] = freezer
}

// IsFrozen says whether the file is read but never a target: a comment declares it frozen, its language's own
// syntax does, or its toolchain regenerates it over any hand edit.
func (f *File) IsFrozen() bool {
	source, err := f.Source()
	if err != nil {
		return false
	}
	language := languageOfPath(f.Path)
	if freezer, declared := freezers[language]; declared && freezer(f) {
		return true
	}
	if language == contract.PHP {
		for _, comment := range f.File.Comments {
			if declaresFreeze(comment.Text) {
				return true
			}
		}

		return false
	}
	for _, line := range strings.Split(string(source), "\n") {
		if isCommentLine(language, line) && declaresFreeze(line) {
			return true
		}
	}

	return isGenerated(language, f.Path, string(source))
}

// languageOfPath is the language a path's extension names, PHP when it names none.
func languageOfPath(path string) contract.Language {
	switch filepath.Ext(path) {
	case ".vue":
		return contract.Vue
	case ".ts":
		return contract.TypeScript
	case ".py":
		return contract.Python
	case ".cs":
		return contract.CSharp
	}

	return contract.PHP
}

func declaresFreeze(comment string) bool {
	return strings.Contains(comment, FrozenMarker) || strings.Contains(comment, GeneratedMarker) || frozenTag.MatchString(comment)
}

// isCommentLine says whether a line opens with its language's comment delimiter.
func isCommentLine(language contract.Language, line string) bool {
	opened := strings.TrimLeft(line, phpSpace)
	switch language {
	case contract.Vue:
		return strings.HasPrefix(opened, "<!--")
	case contract.Python:
		return strings.HasPrefix(opened, "#")
	}

	return strings.HasPrefix(opened, "//") || strings.HasPrefix(opened, "/*") || strings.HasPrefix(opened, "*")
}

// isGenerated says whether a C# file is one its build writes: named as generated code is, or stamped so in its heading.
func isGenerated(language contract.Language, path, source string) bool {
	if language != contract.CSharp {
		return false
	}
	name := strings.ToLower(filepath.Base(path))
	for _, suffix := range []string{".g.cs", ".g.i.cs", ".designer.cs", ".generated.cs"} {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}
	heading := strings.ToLower(headingOf(language, source))

	return strings.Contains(heading, "<auto-generated") || strings.Contains(heading, "<autogenerated")
}

// headingOf is the run of blank and comment lines a source opens with.
func headingOf(language contract.Language, source string) string {
	var heading []string
	for _, line := range strings.Split(trimBytes(source, "\xef\xbb\xbf"), "\n") {
		if strings.Trim(line, phpSpace) != "" && !isCommentLine(language, line) {
			break
		}
		heading = append(heading, line)
	}

	return strings.Join(heading, "\n")
}

// trimBytes drops every leading byte in set, as PHP's ltrim reads its character list byte by byte.
func trimBytes(source, set string) string {
	start := 0
	for start < len(source) && strings.IndexByte(set, source[start]) >= 0 {
		start++
	}

	return source[start:]
}
