<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Tests;

use JesseGall\CodeCommandments\Detectors\Catalog;
use JesseGall\CodeCommandments\Detectors\Repentable;
use JesseGall\CodeCommandments\Scribes\Catalog as Scribes;
use JesseGall\CodeCommandments\Skills\Catalog as Skills;
use PHPUnit\Framework\TestCase;

/**
 * The README.sins.md, README.scribes.md, and README.skills.md tables are
 * auto-generated by `composer readme`. This keeps them honest: every shipped
 * detector, maintenance scribe, and auto-fixable sin must appear, so a new one
 * that skips the regen is caught.
 */
final class ReadmeIsCurrentTest extends TestCase
{
    public function test_every_sin_is_listed_in_the_readme(): void
    {
        $section = $this->tables('README.sins.md');

        foreach (Catalog::all() as $detector) {
            $sin = (new \ReflectionClass($detector->sin()))->getShortName();

            $this->assertStringContainsString(
                "`{$sin}`",
                $section,
                "{$sin} is missing from the README — run `composer readme`.",
            );
        }
    }

    public function test_every_scribe_and_auto_fixable_sin_is_listed_in_the_readme(): void
    {
        $section = $this->tables('README.scribes.md');

        foreach (Scribes::all() as $scribe) {
            $name = (new \ReflectionClass($scribe))->getShortName();
            $this->assertStringContainsString("`{$name}`", $section, "{$name} is missing — run `composer readme`.");
        }

        foreach (Catalog::all() as $detector) {
            if ($detector instanceof Repentable) {
                $sin = (new \ReflectionClass($detector->sin()))->getShortName();
                $this->assertStringContainsString("`{$sin}`", $section, 'an auto-fixable sin is missing — run `composer readme`.');
            }
        }
    }

    public function test_every_skill_is_listed_in_the_readme(): void
    {
        $section = $this->tables('README.skills.md');

        foreach (Skills::all() as $skill) {
            $class = (new \ReflectionClass($skill))->getShortName();
            $this->assertStringContainsString("`{$class}`", $section, "{$skill->slug} ({$class}) is missing — run `composer readme`.");
        }
    }

    private function tables(string $file): string
    {
        $path = __DIR__ . '/../' . $file;

        $this->assertFileExists($path, "{$file} is missing — run `composer readme`.");

        return (string) file_get_contents($path);
    }
}
