<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Tests;

use JesseGall\CodeCommandments\Detectors\Catalog;
use JesseGall\CodeCommandments\Detectors\Repentable;
use JesseGall\CodeCommandments\Scribes\Catalog as Scribes;
use JesseGall\CodeCommandments\Skills\Catalog as Skills;
use PHPUnit\Framework\TestCase;

/**
 * The README "Detectors" and "Auto-fixing" tables are auto-generated by `composer
 * readme`. This keeps them honest: every shipped detector, maintenance scribe, and
 * auto-fixable sin must appear, so a new one that skips the regen is caught.
 */
final class ReadmeIsCurrentTest extends TestCase
{
    public function test_every_sin_is_listed_in_the_readme(): void
    {
        $section = $this->section('detectors');

        foreach (Catalog::all() as $detector) {
            $sin = (new \ReflectionClass($detector->sin()))->getShortName();

            $this->assertStringContainsString(
                "`{$sin}`",
                $section,
                "{$sin} is missing from the README — run `composer readme`.",
            );
        }
    }

    public function test_every_scribe_and_auto_fixable_sin_is_listed_in_the_readme(): void
    {
        $section = $this->section('scribes');

        foreach (Scribes::all() as $scribe) {
            $name = (new \ReflectionClass($scribe))->getShortName();
            $this->assertStringContainsString("`{$name}`", $section, "{$name} is missing — run `composer readme`.");
        }

        foreach (Catalog::all() as $detector) {
            if ($detector instanceof Repentable) {
                $sin = (new \ReflectionClass($detector->sin()))->getShortName();
                $this->assertStringContainsString("`{$sin}`", $section, 'an auto-fixable sin is missing — run `composer readme`.');
            }
        }
    }

    public function test_every_skill_is_listed_in_the_readme(): void
    {
        $section = $this->section('skills');

        foreach (Skills::all() as $skill) {
            $class = (new \ReflectionClass($skill))->getShortName();
            $this->assertStringContainsString("`{$class}`", $section, "{$skill->slug} ({$class}) is missing — run `composer readme`.");
        }
    }

    private function section(string $name): string
    {
        $readme = (string) file_get_contents(__DIR__ . '/../README.md');
        $begin = strpos($readme, "<!-- BEGIN: {$name}");
        $end = strpos($readme, "<!-- END: {$name} -->");

        $this->assertNotFalse($begin, "README {$name} markers not found.");
        $this->assertNotFalse($end);

        return substr($readme, $begin, $end - $begin);
    }
}
