<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Tests;

use JesseGall\CodeCommandments\Detectors\Catalog;
use PHPUnit\Framework\TestCase;

/**
 * The README "Detectors" table is auto-generated by `composer readme`. This keeps
 * it honest: every shipped detector must appear in it, so a new detector that
 * skips the regen is caught.
 */
final class ReadmeIsCurrentTest extends TestCase
{
    public function test_every_detector_is_listed_in_the_readme(): void
    {
        $readme = (string) file_get_contents(__DIR__ . '/../README.md');
        $section = $this->detectorsSection($readme);

        foreach (Catalog::all() as $detector) {
            $name = (new \ReflectionClass($detector))->getShortName();

            $this->assertStringContainsString(
                "`{$name}`",
                $section,
                "{$name} is missing from the README — run `composer readme`.",
            );
        }
    }

    private function detectorsSection(string $readme): string
    {
        $begin = strpos($readme, '<!-- BEGIN: detectors');
        $end = strpos($readme, '<!-- END: detectors -->');

        $this->assertNotFalse($begin, 'README detector markers not found.');
        $this->assertNotFalse($end);

        return substr($readme, $begin, $end - $begin);
    }
}
