<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Tests\Ast\Support;

use JesseGall\CodeCommandments\Ast\Support\Frozen;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * A freeze marker counts where it is DECLARED, never where it is merely spelled (#405) — otherwise a
 * file that documents the feature freezes itself, and every finding in it disappears without a word.
 */
final class FrozenTest extends TestCase
{
    public function test_a_stamp_in_a_comment_freezes_the_file(): void
    {
        $this->assertTrue(Frozen::isFrozen("<?php\n\n// " . Frozen::FILE_MARKER . " — deliberately immutable\n\nclass A {}\n"));
    }

    public function test_a_generated_stamp_in_a_docblock_freezes_the_file(): void
    {
        $this->assertTrue(Frozen::isFrozen("<?php\n\n/**\n * " . Frozen::GENERATED_MARKER . "\n */\nclass A {}\n"));
    }

    public function test_an_at_frozen_tag_freezes_the_file(): void
    {
        $this->assertTrue(Frozen::isFrozen("<?php\n\n/** @frozen */\nclass A {}\n"));
    }

    public function test_the_attribute_freezes_the_file(): void
    {
        $this->assertTrue(Frozen::isFrozen("<?php\n\nuse JesseGall\\CodeCommandments\\Testing\\Frozen;\n\n#[Frozen]\nclass A {}\n"));
    }

    public function test_a_help_text_that_MENTIONS_a_marker_does_not_freeze_the_file(): void
    {
        // The bug, exactly: our own CLI kernel documents the feature in its usage heredoc, and froze
        // itself — hiding real findings from judge and skipping the file in repent, silently.
        $source = <<<'PHP_SOURCE'
        <?php

        final class Kernel
        {
            private const string USAGE = <<<TXT
                commandments judge [path]
                  Files marked @code-commandments-generated are skipped automatically
                TXT;
        }
        PHP_SOURCE;

        $this->assertFalse(Frozen::isFrozen($source));
    }

    public function test_a_string_literal_naming_the_marker_does_not_freeze_the_file(): void
    {
        $this->assertFalse(Frozen::isFrozen("<?php\n\nclass A { public const string M = '" . Frozen::FILE_MARKER . "'; }\n"));
    }

    public function test_a_test_asserting_on_the_stamp_does_not_freeze_itself(): void
    {
        $source = "<?php\n\nclass FreezeTest\n{\n    public function test_it(): void\n    {\n        \$this->assertStringContainsString('@frozen', \$file);\n    }\n}\n";

        $this->assertFalse(Frozen::isFrozen($source));
    }

    public function test_an_ordinary_file_is_not_frozen(): void
    {
        $this->assertFalse(Frozen::isFrozen("<?php\n\nclass A { public function b(): void {} }\n"));
    }

    /**
     * @return array<string, array{string, string, bool}>
     */
    public static function csharpFiles(): array
    {
        return [
            'an auto-generated header' => ['Snapshot.cs', "\u{FEFF}// <auto-generated />\nusing System;\n\nclass Snapshot {}\n", true],
            'the older autogenerated spelling in a block comment' => ['Proto.cs', "/*\n * <autogenerated>\n */\nclass Proto {}\n", true],
            'a source generator\'s file name' => ['Routes.g.cs', "class Routes {}\n", true],
            'a designer file' => ['Form1.Designer.cs', "partial class Form1 {}\n", true],
            'a hand-written file' => ['Order.cs', "// Orders placed by a customer.\nclass Order {}\n", false],
            'the marker below the code, not heading it' => ['Notes.cs', "class Notes {}\n// <auto-generated> is what the tool writes\n", false],
        ];
    }

    #[DataProvider('csharpFiles')]
    public function test_a_csharp_file_the_toolchain_generated_is_frozen(string $name, string $source, bool $frozen): void
    {
        $this->assertSame($frozen, Frozen::isFrozenFile("/project/{$name}", $source));
    }
}
