<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support;

use JesseGall\CodeCommandments\Support\Profiles\Briefing;
use JesseGall\CodeCommandments\Support\Profiles\ProfileOptions;
use JesseGall\PhpTypes\T_String;
use JesseGall\PhpTypes\T_Json;

/**
 * The SINGLE source of truth for the package's Claude Code hook wiring
 * (`.claude/settings.json`). Both runners use it so the artisan (`php artisan
 * commandments:…`) and standalone (`vendor/bin/commandments …`) variants can
 * never drift:
 *
 *  - `install-hooks` / `init` build the wiring with {@see self::build()}.
 *  - `sync` RE-ASSERTS it with {@see self::reassert()} on every package update,
 *    so a NEW hook the package adds (e.g. handoff-detect) reaches existing
 *    consumers automatically — the same guarantee skills, scaffold, and the
 *    .gitignore block already have. Without this, a new SessionStart/Stop hook
 *    was dead-on-arrival until the consumer manually re-ran install-hooks.
 *
 * The merge is idempotent ({@see HookConfigMerger}): our entries are added only
 * when absent, and hand-added hooks are never removed.
 */
final class ClaudeHooksInstaller
{
    public const STATUS_INSTALLED = 'installed';
    public const STATUS_UNCHANGED = 'unchanged';
    public const STATUS_NO_SETTINGS = 'no_settings';
    public const STATUS_WRITE_FAILED = 'write_failed';

    /** The artisan runner: subcommands are colon-suffixed (`php artisan commandments:judge`). */
    public const ARTISAN = ['php artisan commandments', ':'];

    /** The standalone runner: subcommands are space-separated (`vendor/bin/commandments judge`). */
    public const STANDALONE = ['vendor/bin/commandments', ' '];

    /**
     * Hook scripts the package ships (and therefore owns) that don't mention the
     * runner in their command string.
     *
     * @var list<string>
     */
    private const OWNED_SCRIPTS = [
        'handoff-detect.sh',
        'handoff.sh',
        'resume.sh',
        'plan-approved.sh',
        'plan-start.sh',
        'plan-release.sh',
        'keep-going.sh',
        'guard-plan-marker.sh',
        'phase-committed.sh',
        'plan-session-reset.sh',
        'profile-keep-going.sh',
    ];
    /**
     * The runner a CONSUMER PROJECT uses, decided by the project itself (a
     * Laravel app — `artisan` present — documents `php artisan commandments:…`;
     * everything else uses the standalone binary). Detecting from the project,
     * not from which entry point invoked us, means `php artisan commandments:sync`
     * and `vendor/bin/commandments sync` produce IDENTICAL output for the same
     * project — so the wiring never churns between runners.
     *
     * @return array{0: string, 1: string}
     */
    public static function runnerFor(string $basePath): array
    {
        return is_file(rtrim($basePath, '/') . '/artisan') ? self::ARTISAN : self::STANDALONE;
    }

    /**
     * The git post-merge hook body — ONE runner-detecting script (artisan for a
     * Laravel app, else the standalone binary) emitted identically by both
     * install-sync-hook variants, so the auto-sync path can't drift and always
     * runs the same PHP via whichever runner the project uses.
     */
    public static function postMergeHookScript(): string
    {
        return <<<'HOOK'
#!/usr/bin/env sh
# Auto-generated by `commandments install-sync-hook`.
# When composer.lock changed in the incoming merge (a team-mate upgraded a
# dependency, or `composer update` ran), re-sync prophets/scaffold/skills/hooks
# and re-check filed reports — via the runner this project uses (artisan for a
# Laravel app, else the standalone binary), so the auto path never forks.

changed_files="$(git diff-tree -r --name-only ORIG_HEAD HEAD 2>/dev/null)"

printf '%s\n' "$changed_files" | grep -qx 'composer\.lock' || exit 0

if [ -f artisan ]; then
    php artisan commandments:sync --after=previous || true
    php artisan commandments:reports --check 2>/dev/null || true
elif [ -x vendor/bin/commandments ]; then
    vendor/bin/commandments sync --after=previous || true
    vendor/bin/commandments reports --check 2>/dev/null || true
fi
HOOK;
    }

    /**
     * Build the hook events the package owns for a given runner.
     *
     * @param  string  $binary  the runner prefix (e.g. `php artisan commandments`)
     * @param  string  $sep  subcommand separator (`:` for artisan, ` ` for standalone)
     * @return array<string, list<array<string, mixed>>>
     */
    public static function build(string $binary, string $sep, bool $planLoop): array
    {
        $run = static fn (string $sub, string $tail = ' 2>/dev/null || true'): array => [
            'type' => 'command',
            'command' => $binary . $sep . $sub . $tail,
        ];

        $config = [
            'SessionStart' => [
                [
                    'hooks' => [
                        $run('scripture'),
                        $run('reports --check'),
                        $run('scaffold --auto'),
                        $run('install-skills --auto'),
                        $run('skills'),
                        // Binary-independent shell hook — offers a resume when a
                        // HANDOFF.md is present.
                        ['type' => 'command', 'command' => 'sh .claude/hooks/handoff-detect.sh 2>/dev/null || true'],
                    ],
                ],
            ],
            'Stop' => [
                [
                    'hooks' => [
                        $run('judge --git', ' 2>/dev/null; exit 0'),
                    ],
                ],
            ],
            'PostToolUse' => [
                [
                    'matcher' => 'Bash',
                    'hooks' => [
                        ['type' => 'command', 'command' => self::postCommitReminderCommand($binary, $sep)],
                    ],
                ],
            ],
        ];

        // Opt-in plan-loop suite: drives an approved plan to completion. When on,
        // phase-committed.sh supersedes the inline post-commit reminder.
        if ($planLoop) {
            $config['SessionStart'] = [...PlanLoopHookSuite::sessionStartEntries(), ...$config['SessionStart']];
            $config['PreToolUse'] = PlanLoopHookSuite::preToolUseEntries();
            $config['Stop'][] = PlanLoopHookSuite::stopEntry();
            $config['PostToolUse'] = PlanLoopHookSuite::postToolUseEntries();
        }

        return $config;
    }

    /**
     * Build the hook events a PROFILE owns — every agent-awareness entry (the
     * SessionStart briefing, the per-turn drift re-index, the per-phase nudges)
     * is gated on the profile's options, so `disabled` yields an EMPTY owned set
     * (the agent sees nothing) and each active profile installs exactly its bundle.
     * Additive sibling of {@see self::build()} — the legacy signature is untouched.
     *
     * @return array<string, list<array<string, mixed>>>
     */
    public static function buildForProfile(string $binary, string $sep, ProfileOptions $opts, bool $planLoop): array
    {
        $run = static fn (string $sub, string $tail = ' 2>/dev/null || true'): array => [
            'type' => 'command',
            'command' => $binary . $sep . $sub . $tail,
        ];

        $config = [];

        if ($opts->briefAgent) {
            // The profile's concise contract (cadence/gate) ALWAYS briefs at session
            // start; a Full briefing ADDS the scripture (the rules + configured prophets).
            $sessionStart = [$run('profile --brief')];

            if (Briefing::Full->equals($opts->briefing)) {
                $sessionStart[] = $run('scripture');
            }

            $config['SessionStart'] = [
                [
                    'hooks' => [
                        ...$sessionStart,
                        $run('reports --check'),
                        $run('scaffold --auto'),
                        $run('install-skills --auto'),
                        $run('skills'),
                        ['type' => 'command', 'command' => 'sh .claude/hooks/handoff-detect.sh 2>/dev/null || true'],
                        // Re-anchor the contract at session start (also sets the drift baseline).
                        $run('profile --drift-check'),
                    ],
                ],
            ];

            // Per-turn drift re-index: catches a profile change made mid-session by
            // ANY source (this agent, a hand-edit, a teammate's merge, another terminal).
            $config['UserPromptSubmit'] = [
                [
                    'hooks' => [
                        $run('profile --drift-check'),
                    ],
                ],
            ];

            // Plan-mode hook: the moment the agent enters OR finalizes a plan, inject
            // the directive to load + apply the architectural skills, so the plan is
            // designed around the patterns the prophets enforce (not retrofitted later).
            $config['PreToolUse'] = [
                [
                    'matcher' => 'EnterPlanMode|ExitPlanMode',
                    'hooks' => [
                        ['type' => 'command', 'command' => self::planSkillsReminderCommand($binary, $sep)],
                    ],
                ],
            ];
        }

        // Keep-going Stop hook: block stopping until the profile's goal is met. One
        // script self-resolves the active profile at run time. Supersedes the old
        // informational `judge --git` Stop (it judges AND blocks).
        if ($opts->keepGoing) {
            $config['Stop'] = [
                [
                    'hooks' => [
                        ['type' => 'command', 'command' => 'sh .claude/hooks/profile-keep-going.sh'],
                    ],
                ],
            ];
        }

        if ($opts->perPhaseNudges) {
            $config['PostToolUse'] = [
                [
                    'matcher' => 'Bash',
                    'hooks' => [
                        ['type' => 'command', 'command' => self::postCommitReminderCommand($binary, $sep)],
                    ],
                ],
            ];
        }

        if ($planLoop && $opts->briefAgent) {
            $config['SessionStart'] = [...PlanLoopHookSuite::sessionStartEntries(), ...($config['SessionStart'] ?? [])];
            // Append (don't clobber) so the plan-mode skills hook survives.
            $config['PreToolUse'] = [...($config['PreToolUse'] ?? []), ...PlanLoopHookSuite::preToolUseEntries()];
            $config['Stop'] = [...($config['Stop'] ?? []), PlanLoopHookSuite::stopEntry()];
            // grind (no per-phase nudges) keeps the plan-loop DRIVE but drops the
            // per-commit judge nudge — it reckons once at the end, not each phase.
            $config['PostToolUse'] = PlanLoopHookSuite::postToolUseEntries($opts->perPhaseNudges);
        }

        return $config;
    }

    /**
     * A PreToolUse hook (matched to EnterPlanMode/ExitPlanMode): inject the
     * directive to load + apply the architectural skills, so a plan is designed
     * around the patterns the prophets enforce rather than retrofitted afterwards.
     */
    public static function planSkillsReminderCommand(string $binary, string $sep): string
    {
        $r = $binary . $sep;
        $message = 'PLAN MODE with Code Commandments active. Your plan MUST be designed around the architectural patterns the prophets enforce — retrofitting them after the gate blocks you is wasted work. BEFORE finalizing the plan: run `' . $r . 'skills` and READ the skills your work touches (option, invariants, registry, set, null-object, enums, named-exceptions, resolvers, coalesce-factories, immutable-data, model-behaviour), and `' . $r . 'scripture` for the rules. Bake the patterns INTO the plan: Option over null, the right value objects, registries/sets, named exceptions, total functions, no array-bags. A plan that ignores the commandments will fight them.';

        $json = '{"hookSpecificOutput":{"hookEventName":"PreToolUse","additionalContext":"' . $message . '"}}';

        return 'cat >/dev/null 2>&1; printf ' . escapeshellarg($json) . '; exit 0';
    }

    /**
     * A PostToolUse (Bash) hook command: when the tool call was a git commit,
     * inject a reminder to re-read the commandments and resolve every sin.
     */
    public static function postCommitReminderCommand(string $binary, string $sep): string
    {
        $message = 'A commit just landed — a phase is complete. Re-read the Code Commandments '
            . 'section of CLAUDE.md now and act as a sin resolver: run `' . $binary . $sep . 'judge --next --git` '
            . 'and handle every finding before starting the next phase. Fix each sin — even pre-existing ones in '
            . 'files you touched. Warnings: default to FIXING; absolve only when the rubric LEAVE-WHEN genuinely '
            . 'applies, with a reason. Absolve is not a dismiss button. I did not cause this is never a reason to '
            . 'leave a sin in place.';

        $json = '{"hookSpecificOutput":{"hookEventName":"PostToolUse","additionalContext":"' . $message . '"}}';

        return 'in=$(cat); printf "%s" "$in" | grep -q "git commit" && printf '
            . escapeshellarg($json) . '; exit 0';
    }

    /**
     * Re-assert our hooks into `$basePath/.claude/settings.json`, idempotently
     * (new entries added, existing/hand-added ones preserved). Only acts when a
     * settings.json already exists — a routine sync must not impose Claude hooks
     * on a consumer that never opted into them; first-time wiring stays
     * install-hooks/init's job. The runner is detected from the project, so the
     * artisan and standalone entry points yield identical wiring.
     */
    public static function reassert(string $basePath, bool $planLoop): string
    {
        $file = rtrim($basePath, '/') . '/.claude/settings.json';

        if (! is_file($file)) {
            return self::STATUS_NO_SETTINGS;
        }

        $settings = json_decode((string) @file_get_contents($file), true);

        if (! is_array($settings)) {
            $settings = [];
        }

        $before = $settings['hooks'] ?? [];
        $after = self::apply($before, $basePath, $planLoop);

        if ($after === $before) {
            return self::STATUS_UNCHANGED;
        }

        $settings['hooks'] = $after;
        $json = json_encode($settings, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        if ($json === false || @file_put_contents($file, $json . T_String::NEWLINE) === false) {
            return self::STATUS_WRITE_FAILED;
        }

        return self::STATUS_INSTALLED;
    }

    /**
     * Reconcile an existing hooks config to the CURRENT package wiring: every
     * entry the package OWNS is dropped and replaced with the freshly-built set,
     * so a changed/renamed owned hook updates cleanly and a removed one (e.g. the
     * plan-loop suite when its config is turned off) disappears — while EVERY hook
     * the consumer added is preserved untouched. This is what both install-hooks/
     * init and `sync` apply, so the wiring is always the latest version.
     *
     * @param  array<string, list<array<string, mixed>>>  $existing
     * @return array<string, list<array<string, mixed>>>
     */
    public static function apply(array $existing, string $basePath, bool $planLoop): array
    {
        $runner = self::runnerFor($basePath);

        return self::mergeOwned($existing, self::build($runner[0], $runner[1], $planLoop));
    }

    /**
     * Profile-driven sibling of {@see self::apply()}: reconcile the hooks config to
     * the ACTIVE profile's owned set. Switching to a quieter profile drops the
     * entries it no longer owns; switching to `disabled` drops them all — while
     * every hand-added consumer hook is preserved.
     *
     * @param  array<string, list<array<string, mixed>>>  $existing
     * @return array<string, list<array<string, mixed>>>
     */
    public static function applyForProfile(array $existing, string $basePath, ProfileOptions $opts, bool $planLoop): array
    {
        $runner = self::runnerFor($basePath);

        return self::mergeOwned($existing, self::buildForProfile($runner[0], $runner[1], $opts, $planLoop));
    }

    /**
     * Write the active profile's hooks into `$basePath/.claude/settings.json`,
     * preserving consumer hooks. Creates the file for an active profile that owns
     * hooks; for a profile that owns none (disabled), it edits an existing file to
     * strip our entries but never CREATES one (a dormant package leaves no trace).
     *
     * @param  array{0: string, 1: string}  $runner  optional explicit runner; detected otherwise
     */
    public static function writeForProfile(string $basePath, ProfileOptions $opts, bool $planLoop): string
    {
        $file = rtrim($basePath, '/') . '/.claude/settings.json';
        $runner = self::runnerFor($basePath);
        $ours = self::buildForProfile($runner[0], $runner[1], $opts, $planLoop);

        if (! is_file($file)) {
            if ($ours === []) {
                return self::STATUS_NO_SETTINGS;
            }

            @mkdir(dirname($file), 0755, true);
            $settings = ['hooks' => $ours];
            $json = json_encode($settings, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

            if ($json === false || @file_put_contents($file, $json . T_String::NEWLINE) === false) {
                return self::STATUS_WRITE_FAILED;
            }

            return self::STATUS_INSTALLED;
        }

        $settings = json_decode((string) @file_get_contents($file), true);

        if (! is_array($settings)) {
            $settings = [];
        }

        $before = $settings['hooks'] ?? [];
        $after = self::mergeOwned($before, $ours);

        if ($after === $before) {
            return self::STATUS_UNCHANGED;
        }

        if ($after === []) {
            unset($settings['hooks']);
        } else {
            $settings['hooks'] = $after;
        }

        // An emptied settings object must serialize as `{}`, not `[]`.
        $json = $settings === [] ? T_Json::emptyObject() : json_encode($settings, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

        if ($json === false || @file_put_contents($file, $json . T_String::NEWLINE) === false) {
            return self::STATUS_WRITE_FAILED;
        }

        return self::STATUS_INSTALLED;
    }

    /**
     * Replace every package-owned entry with $ours, per event, keeping all
     * consumer-added entries. Shared by {@see self::apply()} and {@see self::applyForProfile()}.
     *
     * @param  array<string, list<array<string, mixed>>>  $existing
     * @param  array<string, list<array<string, mixed>>>  $ours
     * @return array<string, list<array<string, mixed>>>
     */
    private static function mergeOwned(array $existing, array $ours): array
    {
        $result = $existing;
        $events = array_values(array_unique([...array_keys($existing), ...array_keys($ours)]));

        foreach ($events as $event) {
            $kept = array_values(array_filter(
                $existing[$event] ?? [],
                static fn (array $entry): bool => ! self::entryIsOwned($entry),
            ));

            $merged = [...$kept, ...($ours[$event] ?? [])];

            if ($merged === []) {
                unset($result[$event]);
            } else {
                $result[$event] = $merged;
            }
        }

        return $result;
    }

    /**
     * Whether an entry is entirely package-owned (so it is safe to replace). True
     * only when it has commands and EVERY one is recognisably ours — a hand-added
     * or mixed entry is treated as the consumer's and left alone.
     *
     * @param  array<string, mixed>  $entry
     */
    private static function entryIsOwned(array $entry): bool
    {
        $commands = [];

        foreach (($entry['hooks'] ?? []) as $hook) {
            if (isset($hook['command']) && is_string($hook['command'])) {
                $commands[] = $hook['command'];
            }
        }

        if ($commands === []) {
            return false;
        }

        foreach ($commands as $command) {
            if (! self::isOwnedCommand($command)) {
                return false;
            }
        }

        return true;
    }

    /**
     * Whether a hook command is one the package owns — it invokes the commandments
     * runner, or one of the package's own hook scripts.
     */
    private static function isOwnedCommand(string $command): bool
    {
        if (str_contains(strtolower($command), 'commandments')) {
            return true;
        }

        foreach (self::OWNED_SCRIPTS as $script) {
            if (str_contains($command, $script)) {
                return true;
            }
        }

        return false;
    }

}
