<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Skills\CSharp;

use JesseGall\CodeCommandments\Language;
use JesseGall\CodeCommandments\Skills\Skill;
use JesseGall\CodeCommandments\Skills\Tier;

final class Duplication extends Skill
{
    public function __construct()
    {
        parent::__construct(
            slug: 'csharp/duplication',
            tier: Tier::KeepInMind,
            order: 29,
        );
    }

    public function title(): string
    {
        return 'C# duplication — one behaviour, one home';
    }

    public function trigger(): string
    {
        return "Copying a method body from one C# class into another — the same `Map`/`Validate`/`Format` written a second time under another name, or a near-copy that differs only in the key, the path or the message it uses. Read this BEFORE pasting a method you already wrote in another class, and when a duplicate C# function finding points here. The fix is one method both call, parameterised by whatever actually differs.";
    }

    public function intro(): string
    {
        return "A method written twice is one decision living in two places. The day it has to
change, one copy gets the fix and the other keeps the bug — and nothing in either class
says the other exists. In a .NET solution it happens one project at a time: each handler
grows its own `ToDto`, each service its own `BuildQuery`, until the behaviour the system
depends on is spread across classes that do not know about each other.";
    }

    public function summary(): string
    {
        return 'a method body written twice becomes one shared method, parameterised by what differs.';
    }

    public function principle(): string
    {
        return <<<'PRINCIPLE'
### A copy is a decision made twice

Two methods with the same body are the same code whatever they are called — and the case
worth catching is exactly when they are NOT called the same, because then nobody searching
for one finds the other. Hoist the body to ONE home and let every caller use it:

- a method on the type that owns the data, when it reads one object's members;
- an extension method, when the owning type is not yours to change;
- a `static` method in the project both callers already reference, when it only computes;
- a method on a shared base class — or a default interface member — when two
  implementations each wrote the same body.

### A near-copy is a missing parameter

Two bodies with the same control flow that differ only in a literal — a key, a route, an
error message, the text of an interpolated string — are one method waiting for an
argument. Name what differs and pass it; do not keep two copies because the difference "is
only a string". The string is the parameter. When what differs is a type, the parameter is
a generic one.

### What is NOT duplication

Short bodies are alike by coincidence: an expression-bodied one-liner, a property, a
`return _x;` cannot be hoisted into anything smaller than itself. Neither can:

- two constructors of two different classes — each sets its own state;
- two overrides or interface implementations whose shape the contract dictates;
- two stubs that only `throw new NotImplementedException()`;
- two lookup tables — a `switch` expression, a conditional — that call nothing and only
  answer with constants: those are data, not procedure;
- generated code (`// <auto-generated>`, `.g.cs`, `.Designer.cs`) — nobody wrote it by
  hand, and the generator is where it changes.

Duplication is a body of real substance, twice.
PRINCIPLE;
    }

    public function related(): array
    {
        return [
            \JesseGall\CodeCommandments\Skills\Backend\FixAtTheSource::class => 'the root instinct — one decision, made once, where it is born.',
            \JesseGall\CodeCommandments\Skills\Python\Duplication::class => 'the same discipline over Python modules.',
            \JesseGall\CodeCommandments\Skills\TypeScript\Duplication::class => 'the same discipline over TypeScript modules and Vue components.',
        ];
    }

    public function languages(): array
    {
        return [Language::CSharp];
    }
}
