<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Strategies;

/**
 * Every non-null result, gathered into a list — runs the whole chain.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 */
final class CollectResults implements ResolveStrategy
{

    private function __construct() {}

    public static function make(): self
    {
        /** @var self|null $instance */
        static $instance = null;

        return $instance ??= new self();
    }

    /**
     * @return list<mixed>
     */
    public function __invoke(iterable $resolvers, mixed $input): array
    {
        $results = [];

        foreach ($resolvers as $resolve)
        {
            $result = $resolve($input);

            if ($result !== null)
            {
                $results[] = $result;
            }
        }

        return $results;
    }

}
