package catalog

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// Module is the Go module every rule package lives in.
const Module = "github.com/jessegall/code-commandments"

// RuleRoots are the folders whose packages enrol rules from their init functions.
var RuleRoots = []string{"sins", "skill", "detectors"}

// Enrolment is the registry source that imports every rule package under root, so no hand-kept
// list of rules exists: a new rule folder is found by the next go generate.
func Enrolment(root string) ([]byte, error) {
	var packages []string
	for _, rules := range RuleRoots {
		found, err := rulePackages(root, rules)
		if err != nil {
			return nil, err
		}
		packages = append(packages, found...)
	}
	slices.Sort(packages)

	var source bytes.Buffer
	source.WriteString("// Code generated by catalog/enrol; DO NOT EDIT.\n\n")
	source.WriteString("// Package registry enrols every shipped rule: importing it registers each sin, skill and detector.\n")
	source.WriteString("package registry\n\nimport (\n")
	for _, path := range packages {
		fmt.Fprintf(&source, "\t_ %q\n", Module+"/"+path)
	}
	source.WriteString(")\n")

	return format.Source(source.Bytes())
}

// rulePackages is every package folder below one rule root, relative to root, the root itself left out.
func rulePackages(root, rules string) ([]string, error) {
	var packages []string
	base := filepath.Join(root, rules)
	err := filepath.WalkDir(base, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() || path == base {
			return nil
		}
		if name := entry.Name(); name == "testdata" || strings.HasPrefix(name, "_") || strings.HasPrefix(name, ".") {
			return filepath.SkipDir
		}
		if holds, err := holdsGo(path); err != nil || !holds {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		packages = append(packages, filepath.ToSlash(relative))

		return nil
	})

	return packages, err
}

// holdsGo says whether a folder holds a Go source file that is not a test.
func holdsGo(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		if name := entry.Name(); !entry.IsDir() && strings.HasSuffix(name, ".go") && !strings.HasSuffix(name, "_test.go") {
			return true, nil
		}
	}

	return false, nil
}
