package catalog

import (
	"bytes"
	"errors"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// Module is the Go module every rule package lives in.
const Module = "github.com/jessegall/code-commandments"

// RuleRoots are the folders whose packages enrol rules from their init functions: the sins, skills and detectors,
// and the providers that publish one engine's facts for another's detectors.
var RuleRoots = []string{"sins", "skill", "detectors", "published"}

// Enrolment is the registry source that imports every rule package under root, so no hand-kept
// list of rules exists: a new rule folder is found by the next go generate.
func Enrolment(root string) ([]byte, error) {
	var packages []string
	for _, rules := range RuleRoots {
		found, err := rulePackages(root, rules)
		if err != nil {
			return nil, err
		}
		packages = append(packages, found...)
	}
	slices.Sort(packages)

	var source bytes.Buffer
	source.WriteString("// Code generated by catalog/enrol; DO NOT EDIT.\n\n")
	source.WriteString("// Package registry enrols every shipped rule: importing it registers each sin, skill and detector.\n")
	source.WriteString("package registry\n\nimport (\n")
	for _, path := range packages {
		fmt.Fprintf(&source, "\t_ %q\n", Module+"/"+path)
	}
	source.WriteString(")\n")

	return format.Source(source.Bytes())
}

// rulePackages is every package folder below one rule root, relative to root, the root itself left out.
func rulePackages(root, rules string) ([]string, error) {
	var packages []string
	base := filepath.Join(root, rules)
	if _, err := os.Stat(base); errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	err := filepath.WalkDir(base, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !entry.IsDir() || path == base {
			return nil
		}
		if name := entry.Name(); name == "testdata" || strings.HasPrefix(name, "_") || strings.HasPrefix(name, ".") {
			return filepath.SkipDir
		}
		if enrols, err := enrolsRules(path); err != nil || !enrols {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		packages = append(packages, filepath.ToSlash(relative))

		return nil
	})

	return packages, err
}

// enrolsRules says whether a folder's package enrols something when imported: one of its source files, tests aside,
// declares an init function. A folder under a rule root that only renders, generates or helps a test is not one.
func enrolsRules(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		file, err := parser.ParseFile(token.NewFileSet(), filepath.Join(dir, name), nil, parser.SkipObjectResolution)
		if err != nil {
			return false, err
		}
		for _, declaration := range file.Decls {
			if function, ok := declaration.(*ast.FuncDecl); ok && function.Recv == nil && function.Name.Name == "init" {
				return true, nil
			}
		}
	}

	return false, nil
}
