<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Predicates;

use BackedEnum;
use UnitEnum;

/**
 * True when the value is a case of the given enum — either an enum instance,
 * or a backing value (string|int) that maps to a case of a backed enum.
 *
 *     IsEnum::for(NodeType::class)
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @template T of UnitEnum
 *
 * @extends Predicate<T>
 */
final class IsEnum extends Predicate
{

    /**
     * @param  class-string<T>  $enum
     */
    private function __construct(
        private readonly string $enum,
    ) {}

    /**
     * @template TEnum of UnitEnum
     * @param  class-string<TEnum>  $enum
     * @return self<TEnum>
     */
    public static function for(string $enum): self
    {
        return new self($enum);
    }

    public function __invoke(mixed $value): bool
    {
        if ($value instanceof $this->enum)
        {
            return true;
        }

        return (is_string($value) || is_int($value))
            && is_subclass_of($this->enum, BackedEnum::class)
            && $this->enum::tryFrom($value) !== null;
    }

}
