<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Predicates;

/**
 * Inverts a predicate (logical NOT). Built by {@see Predicate::not()} or
 * `Negated::of(...)`.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @template TIn
 *
 * @extends Predicate<TIn>
 */
final class Negated extends Predicate
{

    /**
     * @param  Predicate<TIn>  $predicate
     */
    private function __construct(
        private readonly Predicate $predicate,
    ) {}

    /**
     * @template T
     *
     * @param  Predicate<T>  $predicate
     * @return self<T>
     */
    public static function of(Predicate $predicate): self
    {
        return new self($predicate);
    }

    public function __invoke(mixed $value): bool
    {
        return ! ($this->predicate)($value);
    }

}
