<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Commands;

use Illuminate\Console\Command;
use JesseGall\CodeCommandments\Support\ComposerScriptInstaller;
use JesseGall\CodeCommandments\Support\VersionResolver;

/**
 * Install a git post-merge hook that auto-runs
 * `php artisan commandments:sync --after=previous`
 * when composer.lock changes in an incoming merge.
 */
class InstallSyncHookCommand extends Command
{
    protected $signature = 'commandments:install-sync-hook
        {--force : Overwrite an existing post-merge hook}';

    protected $description = 'Install a git post-merge hook that auto-runs sync --after=previous when composer.lock changes';

    public function handle(): int
    {
        $basePath = base_path();
        $hookPath = $basePath . '/.git/hooks/post-merge';
        $gitDir = dirname($hookPath);

        if (! is_dir(dirname($gitDir))) {
            $this->error('Not a git repository (no .git directory found).');

            return self::FAILURE;
        }

        if (! is_dir($gitDir)) {
            @mkdir($gitDir, 0755, true);
        }

        if (is_file($hookPath) && ! $this->option('force')) {
            $this->warn("Hook already exists at {$hookPath}. Re-run with --force to overwrite.");

            return self::SUCCESS;
        }

        if (@file_put_contents($hookPath, $this->hookScript()) === false) {
            $this->error("Failed to write {$hookPath}");

            return self::FAILURE;
        }

        @chmod($hookPath, 0755);

        $this->info('Installed git post-merge hook at .git/hooks/post-merge');

        $this->installComposerScript($basePath);
        $this->recordBaselineVersion($basePath);

        $this->newLine();
        $this->line('Now every <info>git pull</info> and <info>composer update</info> will run sync automatically.');

        return self::SUCCESS;
    }

    private function installComposerScript(string $basePath): void
    {
        $composerJson = $basePath . '/composer.json';
        $installer = new ComposerScriptInstaller();
        $command = '@php artisan commandments:sync --after=previous';

        $status = $installer->install($composerJson, 'post-update-cmd', $command);

        match ($status) {
            ComposerScriptInstaller::STATUS_INSTALLED => $this->info(
                'Added artisan commandments:sync --after=previous to composer.json post-update-cmd'
            ),
            ComposerScriptInstaller::STATUS_ALREADY_PRESENT => $this->line(
                'composer.json already has the sync script — skipped'
            ),
            ComposerScriptInstaller::STATUS_MISSING_FILE => $this->warn(
                'No composer.json found — skipping composer-script install.'
            ),
            ComposerScriptInstaller::STATUS_INVALID_JSON => $this->error(
                'composer.json is not valid JSON — skipping composer-script install. Add the script manually.'
            ),
            ComposerScriptInstaller::STATUS_WRITE_FAILED => $this->error(
                'Failed to write composer.json — check permissions.'
            ),
        };
    }

    private function recordBaselineVersion(string $basePath): void
    {
        $resolver = new VersionResolver();
        $current = $resolver->currentVersion();

        if ($current === null) {
            $this->warn('Could not resolve installed package version (dev install?) — skipping baseline record.');

            return;
        }

        if ($resolver->recordSyncedVersion($basePath, $current)) {
            $this->info("Recorded baseline sync version {$current} in .commandments-last-synced");
        } else {
            $this->warn('Failed to write .commandments-last-synced — check permissions.');
        }
    }

    private function hookScript(): string
    {
        return <<<'HOOK'
#!/usr/bin/env sh
# Auto-generated by `artisan commandments:install-sync-hook`.
# Runs `artisan commandments:sync --after=previous` when composer.lock
# changed in the incoming merge (a team-mate upgraded a dependency).

changed_files="$(git diff-tree -r --name-only ORIG_HEAD HEAD 2>/dev/null)"

if printf '%s\n' "$changed_files" | grep -qx 'composer\.lock'; then
    if [ -x artisan ]; then
        php artisan commandments:sync --after=previous || true
    fi
fi

HOOK;
    }
}
