<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Commands;

use Illuminate\Console\Command;

/**
 * Install a git post-merge hook that auto-runs
 * `php artisan commandments:sync --after=previous`
 * when composer.lock changes in an incoming merge.
 */
class InstallSyncHookCommand extends Command
{
    protected $signature = 'commandments:install-sync-hook
        {--force : Overwrite an existing post-merge hook}';

    protected $description = 'Install a git post-merge hook that auto-runs sync --after=previous when composer.lock changes';

    public function handle(): int
    {
        $basePath = base_path();
        $hookPath = $basePath . '/.git/hooks/post-merge';
        $gitDir = dirname($hookPath);

        if (! is_dir(dirname($gitDir))) {
            $this->error('Not a git repository (no .git directory found).');

            return self::FAILURE;
        }

        if (! is_dir($gitDir)) {
            @mkdir($gitDir, 0755, true);
        }

        if (is_file($hookPath) && ! $this->option('force')) {
            $this->warn("Hook already exists at {$hookPath}. Re-run with --force to overwrite.");

            return self::SUCCESS;
        }

        if (@file_put_contents($hookPath, $this->hookScript()) === false) {
            $this->error("Failed to write {$hookPath}");

            return self::FAILURE;
        }

        @chmod($hookPath, 0755);

        $this->info("Installed git post-merge hook at .git/hooks/post-merge");
        $this->newLine();
        $this->line('Fires on <info>git pull</info> / <info>git merge</info> when composer.lock changes.');
        $this->line('For <info>composer update</info> integration too, add this to your composer.json:');
        $this->newLine();
        $this->line('  "scripts": {');
        $this->line('    "post-update-cmd": [');
        $this->line('      "@php artisan commandments:sync --after=previous"');
        $this->line('    ]');
        $this->line('  }');

        return self::SUCCESS;
    }

    private function hookScript(): string
    {
        return <<<'HOOK'
#!/usr/bin/env sh
# Auto-generated by `artisan commandments:install-sync-hook`.
# Runs `artisan commandments:sync --after=previous` when composer.lock
# changed in the incoming merge (a team-mate upgraded a dependency).

changed_files="$(git diff-tree -r --name-only ORIG_HEAD HEAD 2>/dev/null)"

if printf '%s\n' "$changed_files" | grep -qx 'composer\.lock'; then
    if [ -x artisan ]; then
        php artisan commandments:sync --after=previous || true
    fi
fi

HOOK;
    }
}
