<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Scaffolding;

use JesseGall\PhpTypes\T_String;

/**
 * Stamps the package's support-class stubs into the consumer's namespace,
 * rewriting the namespace to the configured one. Idempotent: an existing
 * file is never overwritten unless $force is set.
 */
final class ScaffoldGenerator
{
    public const STATUS_CREATED = 'created';
    public const STATUS_SKIPPED = 'skipped';
    public const STATUS_REWRITTEN = 'rewritten';
    public const STATUS_MISSING_STUB = 'missing_stub';

    public function __construct(
        private readonly string $stubDir,
    ) {}

    public static function packaged(): self
    {
        return new self(__DIR__ . '/../../../stubs/scaffold');
    }

    /**
     * @param  list<string>  $except  scaffold names to skip
     * @return list<array{name: string, class: string, status: string}>
     */
    public function generate(string $namespace, string $path, bool $force = false, array $except = [], bool $autoRefresh = false): array
    {
        $namespace = trim($namespace, '\\');
        $results = [];

        foreach (ScaffoldRegistry::all() as $scaffold) {
            if (in_array($scaffold->name, $except, true)) {
                continue;
            }

            $sub = T_String::isNotEmpty($scaffold->subNamespace) ? '\\' . trim($scaffold->subNamespace, '\\') : T_String::empty();

            $results[] = [
                'name' => $scaffold->name,
                'class' => $namespace . $sub . '\\' . $scaffold->className,
                'status' => $this->write($scaffold, $namespace, $path, $force, $autoRefresh),
            ];
        }

        return $results;
    }

    private function write(Scaffold $scaffold, string $namespace, string $path, bool $force, bool $autoRefresh = false): string
    {
        $stubPath = $this->stubDir . '/' . $scaffold->stubFile;

        if (! is_file($stubPath)) {
            return self::STATUS_MISSING_STUB;
        }

        $stub = $this->applyHeader((string) file_get_contents($stubPath), $autoRefresh);

        // A consumer may have relocated a generated class into a sub-namespace
        // (e.g. `Support\Enums\CompareSelf`). Find it by its generated marker
        // wherever it lives under the scaffold path and refresh it IN PLACE,
        // preserving the namespace it was moved to — otherwise a re-scaffold
        // would silently write a stale duplicate at the flat path and the
        // consumer's real class would never receive the fix.
        $existing = $this->locateExisting($scaffold->className, $path);

        if ($existing !== null) {
            if (! $force) {
                return self::STATUS_SKIPPED;
            }

            $existingNamespace = $this->namespaceOf($existing) ?? $namespace;
            $contents = str_replace('{{ namespace }}', $existingNamespace, $stub);

            if (@file_put_contents($existing, $contents) === false) {
                return self::STATUS_SKIPPED;
            }

            return self::STATUS_REWRITTEN;
        }

        // A class may declare a sub-namespace (e.g. `Resolvers\Predicates`),
        // which becomes both a directory under the scaffold path and a suffix
        // on the namespace.
        $targetDir = rtrim($path, '/');
        $targetNamespace = $namespace;

        if (T_String::isNotEmpty($scaffold->subNamespace)) {
            $targetDir .= '/' . str_replace('\\', '/', trim($scaffold->subNamespace, '\\'));
            $targetNamespace .= '\\' . trim($scaffold->subNamespace, '\\');
        }

        $target = $targetDir . '/' . $scaffold->className . '.php';
        $exists = is_file($target);

        if ($exists && ! $force) {
            return self::STATUS_SKIPPED;
        }

        $contents = str_replace('{{ namespace }}', $targetNamespace, $stub);

        if (! is_dir($targetDir)) {
            @mkdir($targetDir, 0755, true);
        }

        if (@file_put_contents($target, $contents) === false) {
            return self::STATUS_SKIPPED;
        }

        return $exists ? self::STATUS_REWRITTEN : self::STATUS_CREATED;
    }

    /**
     * Swap the stub's "safe to edit" line for a LOUD do-not-edit banner when
     * auto-refresh is on — these files are regenerated automatically, so any
     * hand-edit is doomed.
     */
    private function applyHeader(string $stub, bool $autoRefresh): string
    {
        if (! $autoRefresh) {
            return $stub;
        }

        $banner = '!!  AUTO-GENERATED — DO NOT EDIT THIS FILE  !!'
            . "\n *"
            . "\n * scaffold.auto_refresh is ON: code-commandments REGENERATES this file"
            . "\n * automatically, so ANY CHANGE YOU MAKE HERE WILL BE OVERWRITTEN. Edit the"
            . "\n * package stub instead, or set scaffold.auto_refresh = false to own it by hand.";

        return str_replace('Generated by code-commandments — safe to edit.', $banner, $stub);
    }

    /**
     * Find an already-generated copy of $className anywhere under $path,
     * identified by the generated marker (so a consumer's hand-relocated copy
     * is matched, not just the flat default path). Returns its absolute path
     * or null.
     */
    private function locateExisting(string $className, string $path): ?string
    {
        if (! is_dir($path)) {
            return null;
        }

        // Built from parts so this source file does not itself carry the
        // literal marker (which would make the scroll judge skip it).
        $marker = '@code-commandments' . '-generated';
        $needle = $className . '.php';

        try {
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($path, \FilesystemIterator::SKIP_DOTS),
            );
        } catch (\Throwable) {
            return null;
        }

        foreach ($iterator as $file) {
            if (! $file instanceof \SplFileInfo || $file->getFilename() !== $needle) {
                continue;
            }

            $real = $file->getRealPath();

            if ($real === false) {
                continue;
            }

            $contents = @file_get_contents($real);

            if ($contents !== false && str_contains($contents, $marker)) {
                return $real;
            }
        }

        return null;
    }

    private function namespaceOf(string $file): ?string
    {
        $contents = @file_get_contents($file);

        if ($contents === false) {
            return null;
        }

        if (preg_match('/^\s*namespace\s+([^;]+);/m', $contents, $m) === 1) {
            return trim($m[1]);
        }

        return null;
    }
}
