package doc

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/jessegall/code-commandments/catalog"
	"github.com/jessegall/code-commandments/cli/agents"
	"github.com/jessegall/code-commandments/cli/block"
	"github.com/jessegall/code-commandments/cli/config"
	"github.com/jessegall/code-commandments/cli/hooks"
	"github.com/jessegall/code-commandments/cli/jsonfile"
	"github.com/jessegall/code-commandments/cli/library"
	"github.com/jessegall/code-commandments/cli/source"
	"github.com/jessegall/code-commandments/cli/workspace"
	"github.com/jessegall/code-commandments/detectors"
	"github.com/jessegall/code-commandments/scribes"
	"github.com/jessegall/code-commandments/sins"
	"github.com/jessegall/code-commandments/skill"
)

// Table is one generated table: the file it is written to, its title, its body, and the excerpt README.md keeps
// in its block.
type Table struct {
	Block   string
	File    string
	Title   string
	Body    string
	Excerpt string
}

// Document is the table's file: its title, the note that it is generated, and its body.
func (t Table) Document() string {
	return "# " + t.Title + "\n\nAuto-generated by `composer readme`; do not edit by hand. Part of [README.md](README.md).\n" + t.Body
}

// Tables are the sins, the auto-fixes and the skills, each a file of its own that README.md excerpts.
func Tables() []Table {
	return []Table{skillsTable(), sinsTable(), scribesTable()}
}

// engines are the engines the skills name, read off their slugs, in name order.
func engines() []string {
	var found []string
	for _, teaching := range skill.All() {
		engine, _, _ := strings.Cut(teaching.Definition().Slug, "/")
		if !slices.Contains(found, engine) {
			found = append(found, engine)
		}
	}
	slices.Sort(found)

	return found
}

// heading is an engine's heading: backend reads as Backend, typescript as TypeScript.
func heading(engine string) string {
	if engine == "typescript" {
		return "TypeScript"
	}

	return strings.ToUpper(engine[:1]) + engine[1:]
}

// bound says whether the sin holds only in a project with a package, such as Spatie Data; those sort after the
// universal ones.
func bound(sin sins.Sin) int {
	if sin.Definition().Requires.Name != "" {
		return 1
	}

	return 0
}

// sinsTable is every detector, grouped by the skill its sin points at, the universal skills first.
func sinsTable() Table {
	bySkill := map[string][]detectors.Detector{}
	var slugs []string
	for _, detector := range config.InClassOrder(config.Detector, detectors.All()) {
		slug := detector.Sin().Definition().Slug()
		if _, seen := bySkill[slug]; !seen {
			slugs = append(slugs, slug)
		}
		bySkill[slug] = append(bySkill[slug], detector)
	}
	slices.SortFunc(slugs, func(a, b string) int {
		if first, second := bound(bySkill[a][0].Sin()), bound(bySkill[b][0].Sin()); first != second {
			return first - second
		}

		return strings.Compare(a, b)
	})
	total := len(detectors.All())
	lines := []string{fmt.Sprintf("_%d sins across %d skills._\n", total, len(slugs))}
	for _, engine := range engines() {
		lines = append(lines, "### "+heading(engine)+"\n")
		for _, slug := range slugs {
			if !strings.HasPrefix(slug, engine+"/") {
				continue
			}
			lines = append(lines, "#### `"+slug+"`\n", "| Sin | What it flags |", "|---|---|")
			for _, detector := range bySkill[slug] {
				lines = append(lines, "| `"+catalog.Name(detector.Sin())+"` | "+cell(detector.Sin().Definition().Description)+" |")
			}
			lines = append(lines, "")
		}
	}

	return Table{
		Block:   "detectors",
		File:    "README.sins.md",
		Title:   "Sins & detectors",
		Body:    "\n" + strings.Join(lines, "\n") + "\n",
		Excerpt: fmt.Sprintf("_%d sins across %d skills. Full tables in [README.sins.md](README.sins.md)._", total, len(slugs)),
	}
}

// scribesTable is the whole-tree maintenance passes and, engine by engine, every sin repent fixes.
func scribesTable() Table {
	var repentables []detectors.Detector
	for _, detector := range detectors.All() {
		if _, repents := detector.(detectors.Repentable); repents {
			repentables = append(repentables, detector)
		}
	}
	slices.SortStableFunc(repentables, func(a, b detectors.Detector) int {
		if first, second := bound(a.Sin()), bound(b.Sin()); first != second {
			return first - second
		}
		if order := strings.Compare(a.Sin().Definition().Slug(), b.Sin().Definition().Slug()); order != 0 {
			return order
		}

		return strings.Compare(a.Sin().Definition().Name, b.Sin().Definition().Name)
	})
	maintainers := scribes.Maintainers()
	counts := fmt.Sprintf("`repent` auto-fixes %d sins, plus %d whole-tree maintenance passes", len(repentables), len(maintainers))
	lines := []string{"_" + counts + "._", "", "### Maintenance passes", "", "Whole-tree PHP rewrites, run on every `repent`:", "", "| Scribe | What it does |", "|---|---|"}
	for _, maintainer := range maintainers {
		lines = append(lines, "| `"+maintainer.Name()+"` | "+cell(maintainer.Summary())+" |")
	}
	lines = append(lines, "")
	for _, engine := range engines() {
		lines = append(lines, "### "+heading(engine), "")
		var rows []string
		for _, detector := range repentables {
			if strings.HasPrefix(detector.Sin().Definition().Slug(), engine+"/") {
				rows = append(rows, "| `"+catalog.Name(detector.Sin())+"` | "+cell(detector.Sin().Definition().Rule)+" |")
			}
		}
		if len(rows) > 0 {
			lines = append(append(lines, "| Sin | The fix `repent` applies |", "|---|---|"), rows...)
		}
		lines = append(lines, "")
	}

	return Table{
		Block:   "scribes",
		File:    "README.scribes.md",
		Title:   "Auto-fixing",
		Body:    "\n" + strings.Join(lines, "\n") + "\n",
		Excerpt: "_" + counts + ". Full tables in [README.scribes.md](README.scribes.md)._",
	}
}

// skillsTable is every skill, engine by engine, with the one line it teaches.
func skillsTable() Table {
	taught := skill.All()
	slices.SortStableFunc(taught, func(a, b skill.Skill) int {
		return strings.Compare(a.Definition().Slug, b.Definition().Slug)
	})
	lines := []string{fmt.Sprintf("_%d skills._", len(taught)), ""}
	for _, engine := range engines() {
		lines = append(lines, "### "+heading(engine), "", "| Skill | What it teaches |", "|---|---|")
		for _, teaching := range taught {
			if strings.HasPrefix(teaching.Definition().Slug, engine+"/") {
				lines = append(lines, "| `"+catalog.Name(teaching)+"` | "+cell(strings.Join(strings.Fields(teaching.Definition().Summary), " "))+" |")
			}
		}
		lines = append(lines, "")
	}

	return Table{
		Block:   "skills",
		File:    "README.skills.md",
		Title:   "Skills",
		Body:    "\n" + strings.Join(lines, "\n") + "\n",
		Excerpt: fmt.Sprintf("_%d skills. Full table in [README.skills.md](README.skills.md)._", len(taught)),
	}
}

// HooksTable is every hook the tool ships: the moments it listens for, and what it does.
func HooksTable() string {
	rows := "| Hook | Events | What it does |\n|---|---|---|\n"
	for _, hook := range hooks.Builtins() {
		var events []string
		for _, binding := range hook.Bindings() {
			if !slices.Contains(events, binding.Label()) {
				events = append(events, binding.Label())
			}
		}
		rows += "| `" + hook.Class() + "` | `" + strings.Join(events, ", ") + "` | " + strings.ReplaceAll(hook.Summary(), "|", `\|`) + " |\n"
	}

	return rows
}

// AgentsTable is every agent the curriculum is published for: where it reads skills and instructions from, and
// whether its disciplines are enforced.
func AgentsTable() string {
	rows := []string{"| Agent | Skills | Instructions | Enforced by hooks | What it gets |", "|---|---|---|---|---|"}
	for _, agent := range agents.All() {
		skills := "`" + agent.SkillsDir() + "` _(links)_"
		if agent.SkillsDir() == "" {
			skills = "`" + workspace.Library + "` _(read directly)_"
		}
		instructions := agent.InstructionsFile()
		if instructions == "" {
			instructions = "AGENTS.md"
		}
		enforced := "no"
		if agent.Enforces() {
			enforced = "yes"
		}
		rows = append(rows, "| **"+agent.Name()+"** | "+skills+" | `"+instructions+"` | "+enforced+" | "+agent.Summary()+" |")
	}

	return strings.Join(rows, "\n") + "\n"
}

// PluginSettings is the journal plugin's settings: the folders judged and left out, a switch per language, and a
// switch per sin, grouped by its skill — so the plugin's Settings panel never names a rule that is gone.
func PluginSettings() *jsonfile.Object {
	settings := jsonfile.NewObject(
		"folders_judged", setting("Folders to check", "One folder per line, from the project root. Empty, the config keeps the folders it names.", "list", "", "Folders"),
		"folders_skipped", setting("Folders to leave out", "One folder per line, never read or reported, such as generated code. This list is what the config leaves out.", "list", "", "Folders"),
	)
	for _, language := range source.Languages {
		settings.Set("language_"+string(language), setting(language.Label(), "Enables "+language.Label()+" sin detection", "flag", "true", "Languages"))
	}
	ordered := slices.Clone(detectors.All())
	slices.SortStableFunc(ordered, func(a, b detectors.Detector) int {
		if order := strings.Compare(a.Sin().Definition().Slug(), b.Sin().Definition().Slug()); order != 0 {
			return order
		}

		return strings.Compare(a.Sin().Definition().Name, b.Sin().Definition().Name)
	})
	for _, detector := range ordered {
		definition := detector.Sin().Definition()
		when := []any{}
		for _, name := range definition.Skill.Definition().Languages {
			if language, known := library.LanguageOf(name); known {
				when = append(when, jsonfile.NewObject("language_"+string(language), true))
			}
		}
		entry := setting(catalog.Name(detector.Sin()), definition.Description, "flag", "true", definition.Slug())
		entry.Set("when", when)
		entry.Set("detail", true)
		settings.Set("sin_"+definition.Name, entry)
	}

	return settings
}

func setting(title, help, kind, fallback, group string) *jsonfile.Object {
	return jsonfile.NewObject("title", title, "help", help, "type", kind, "default", fallback, "group", group)
}

// Plugin is the journal plugin's manifest, whose settings are the registry's and the rest hand-kept.
const Plugin = ".journal-plugin/plugin.json"

// Generated is what every generated document under root holds today, by its path under root: each table's file,
// README.md with each table's excerpt and the hooks and agents tables in their blocks, and the plugin's manifest
// with its settings.
func Generated(root string) (map[string]string, error) {
	readme, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		return nil, err
	}
	documents := map[string]string{}
	updated := string(readme)
	for _, table := range Tables() {
		documents[table.File] = table.Document()
		if updated, err = replaced(updated, table.Block, "\n"+table.Excerpt+"\n"); err != nil {
			return nil, err
		}
	}
	for name, content := range map[string]string{"hooks-table": HooksTable(), "agents-table": AgentsTable()} {
		if updated, err = replaced(updated, name, "\n"+content); err != nil {
			return nil, err
		}
	}
	documents["README.md"] = updated
	manifest, read := jsonfile.Read(filepath.Join(root, Plugin))
	if !read {
		return nil, fmt.Errorf("%s is not a JSON object", Plugin)
	}
	manifest.Set("settings", PluginSettings())
	documents[Plugin] = jsonfile.Text(manifest)

	return documents, nil
}

// replaced is the document with the block's content replaced; a document without the block is a mistake.
func replaced(document, name, content string) (string, error) {
	updated, found, err := block.Replace(document, name, content)
	if err != nil {
		return "", err
	}
	if !found {
		return "", fmt.Errorf("README.md holds no %s block", name)
	}

	return updated, nil
}
