<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Tests\Detectors\CSharp;

use JesseGall\CodeCommandments\Cs\Codebase;
use JesseGall\CodeCommandments\Detectors\CSharp\AssembledTemplateDetector;
use JesseGall\CodeCommandments\Tests\Cs\NeedsTheBridge;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Three or more lines written right there, joined with a newline, are a template taken apart; joining computed
 * values, joining into one line, and two lines are fine.
 */
final class AssembledTemplateDetectorTest extends TestCase
{
    use NeedsTheBridge;

    protected function setUp(): void
    {
        $this->requireTheBridge();
    }

    /**
     * @return array<string, array{string, int}>
     */
    public static function members(): array
    {
        return [
            'an array joined with \\n' => ['public static string Class(string name) => string.Join("\n", new[] { $"public class {name}", "{", "}" });', 1],
            'params joined with Environment.NewLine' => ['public static string Mail(string who) => string.Join(System.Environment.NewLine, $"Dear {who},", "", "Thanks for your order.");', 1],
            'a collection expression' => ['public static string Block(string key) => string.Join("\r\n", (string[])["[section]", $"key = {key}", "enabled = true"]);', 1],
            'a run of AppendLine' => ['public static string Header(System.Text.StringBuilder sb, string ns) { sb.AppendLine("// <auto-generated/>"); sb.AppendLine("#nullable enable"); sb.AppendLine($"namespace {ns};"); return sb.ToString(); }', 1],
            'AppendLine of computed values' => ['public static void Lines(System.Text.StringBuilder sb, string a, string b, string c) { sb.AppendLine(a); sb.AppendLine(b); sb.AppendLine(c); }', 0],
            'two AppendLine calls' => ['public static void Two(System.Text.StringBuilder sb) { sb.AppendLine("a"); sb.AppendLine("b"); }', 0],
            'computed values' => ['public static string List(string[] names) => string.Join("\n", names);', 0],
            'one line' => ['public static string Row(string a, string b, string c) => string.Join(", ", new[] { a, b, c });', 0],
            'two lines' => ['public static string Pair(string name) => string.Join("\n", new[] { "Hello", name });', 0],
        ];
    }

    #[DataProvider('members')]
    public function test_flags_lines_joined_into_a_template(string $member, int $flagged): void
    {
        $source = "public static class Writer\n{\n    {$member}\n}\n";
        $this->assertCount($flagged, new AssembledTemplateDetector()->find(Codebase::fromString($source, 'Writer.cs')), $source);
    }
}
