<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support;

/**
 * A {@see Union} constrained to the scalar types — `string | int | float | bool`.
 * The ready-made named home for the most common wide union: a present value
 * that is some scalar (a config primitive, a default value, a cell). `of()`
 * rejects anything non-scalar (and null — reach for {@see Option} when it can
 * be absent).
 *
 *     $default = ScalarUnion::of($value);     // throws unless string|int|float|bool
 *
 *     $rendered = $default->match([
 *         'bool'   => fn (bool $b) => $b ? 'yes' : 'no',
 *         'string' => fn (string $s) => $s,
 *         'int'    => fn (int $i) => (string) $i,
 *         'float'  => fn (float $f) => rtrim(rtrim(number_format($f, 4), '0'), '.'),
 *     ]);
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @extends Union<string|int|float|bool>
 */
final class ScalarUnion extends Union
{

    protected function allowedTypes(): array
    {
        return ['string', 'int', 'float', 'bool'];
    }

}
