<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments;

/**
 * The language a worked example is written in — what fences its code block, and what labels it when
 * one skill teaches a discipline more than one language has.
 *
 * A fact about the FIXTURE the example came from, never a guess from the sin that points at it: a
 * frontend rule's example is a template when it was marked in a `.vue` file and a module when it was
 * marked in a `.ts` one, and only the file knows which.
 */
enum Language: string
{
    case Php = 'php';

    case Vue = 'vue';

    case TypeScript = 'ts';
    case Python = 'py';
    case CSharp = 'cs';

    /**
     * The language of the file at $path — the one place an extension is read as a language.
     */
    public static function ofFile(string $path): self
    {
        return match (true) {
            str_ends_with($path, '.vue') => self::Vue,
            str_ends_with($path, '.ts') => self::TypeScript,
            str_ends_with($path, '.py') => self::Python,
            str_ends_with($path, '.cs') => self::CSharp,
            default => self::Php,
        };
    }

    /**
     * Is the file at $path written in a language judge reads? Each case's value IS its extension, so
     * a language added here is judged everywhere a path is filtered — never behind a list of its own.
     */
    public static function judges(string $path): bool
    {
        return self::tryFrom(pathinfo($path, PATHINFO_EXTENSION)) !== null;
    }

    /**
     * The engine that reads a file of this language — PHP the backend's, a component and a TypeScript
     * module the frontend's, Python and C# each their own.
     */
    public function engine(): Engine
    {
        return match ($this) {
            self::Php => Engine::Backend,
            self::Vue, self::TypeScript => Engine::Frontend,
            self::Python => Engine::Python,
            self::CSharp => Engine::CSharp,
        };
    }

    /**
     * $text as a comment of this language on a line of its own — how a stamp is written into a file.
     */
    public function comment(string $text): string
    {
        return match ($this) {
            self::Php, self::TypeScript, self::CSharp => "// {$text}",
            self::Vue => "<!-- {$text} -->",
            self::Python => "# {$text}",
        };
    }

    /**
     * Does $line carry a comment of this language — a line a declaration in a comment can be read
     * from? Read off the delimiter the line opens with, never its words.
     */
    public function isCommentLine(string $line): bool
    {
        $opened = ltrim($line);

        return match ($this) {
            self::Php, self::TypeScript, self::CSharp => str_starts_with($opened, '//') || str_starts_with($opened, '/*') || str_starts_with($opened, '*'),
            self::Vue => str_starts_with($opened, '<!--'),
            self::Python => str_starts_with($opened, '#'),
        };
    }

    /**
     * Did its language's own toolchain generate the file at $path? C# says so the way Roslyn reads it:
     * a generated file's name (`.g.cs`, `.designer.cs`, `.generated.cs`), or an `<auto-generated>` stamp
     * in the comments that head the file. The other languages mark theirs with the generated stamp every
     * language shares ({@see \JesseGall\CodeCommandments\Ast\Support\Frozen::GENERATED_MARKER}).
     */
    public function isGenerated(string $path, string $source): bool
    {
        if ($this !== self::CSharp) {
            return false;
        }

        $name = strtolower(basename($path));

        return array_any(['.g.cs', '.g.i.cs', '.designer.cs', '.generated.cs'], static fn (string $suffix): bool => str_ends_with($name, $suffix))
            || array_any(['<auto-generated', '<autogenerated'], fn (string $stamp): bool => str_contains(strtolower($this->heading($source)), $stamp));
    }

    /**
     * The comment lines a file opens with, before its first line of code.
     */
    private function heading(string $source): string
    {
        $heading = [];

        foreach (explode("\n", ltrim($source, "\u{FEFF}")) as $line) {
            if (trim($line) !== '' && ! $this->isCommentLine($line)) {
                break;
            }

            $heading[] = $line;
        }

        return implode("\n", $heading);
    }

    /**
     * How a reader is told which language an example is in, when a skill shows more than one.
     */
    public function label(): string
    {
        return match ($this) {
            self::Php => 'PHP',
            self::Vue => 'Vue',
            self::TypeScript => 'TypeScript',
            self::Python => 'Python',
            self::CSharp => 'C#',
        };
    }

    /**
     * The language $text names by its {@see label} — how a rendered example heading says which one
     * it is in. Null when it names none, which is every other line of a document.
     */
    public static function namedIn(string $text): ?self
    {
        foreach (self::cases() as $language) {
            if (str_ends_with(rtrim($text), '— in ' . $language->label())) {
                return $language;
            }
        }

        return null;
    }
}
