<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Console;

use JesseGall\CodeCommandments\Support\Environment;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Install a git post-merge hook that runs `sync --after=previous` whenever
 * composer.lock changes in an incoming merge (typical team-mate upgrade flow).
 */
class InstallSyncHookConsoleCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->setName('install-sync-hook')
            ->setDescription('Install a git post-merge hook that auto-runs `sync --after=previous` when composer.lock changes')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Overwrite an existing post-merge hook');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $basePath = getcwd();
        Environment::setBasePath($basePath);

        $hookPath = $basePath . '/.git/hooks/post-merge';
        $gitDir = dirname($hookPath);

        if (! is_dir(dirname($gitDir))) {
            $output->writeln('<error>Not a git repository (no .git directory found).</error>');

            return Command::FAILURE;
        }

        if (! is_dir($gitDir)) {
            @mkdir($gitDir, 0755, true);
        }

        if (is_file($hookPath) && ! $input->getOption('force')) {
            $output->writeln("<comment>Hook already exists at {$hookPath}. Re-run with --force to overwrite.</comment>");

            return Command::SUCCESS;
        }

        $content = $this->hookScript();

        if (@file_put_contents($hookPath, $content) === false) {
            $output->writeln("<error>Failed to write {$hookPath}</error>");

            return Command::FAILURE;
        }

        @chmod($hookPath, 0755);

        $relative = str_starts_with($hookPath, $basePath)
            ? ltrim(str_replace($basePath, '', $hookPath), '/')
            : $hookPath;

        $output->writeln("Installed git post-merge hook at {$relative}");
        $output->writeln('');
        $output->writeln('Fires on <info>git pull</info> / <info>git merge</info> when composer.lock changes.');
        $output->writeln('For <info>composer update</info> integration too, add this to your composer.json:');
        $output->writeln('');
        $output->writeln('  "scripts": {');
        $output->writeln('    "post-update-cmd": [');
        $output->writeln('      "vendor/bin/commandments sync --after=previous"');
        $output->writeln('    ]');
        $output->writeln('  }');

        return Command::SUCCESS;
    }

    private function hookScript(): string
    {
        return <<<'HOOK'
#!/usr/bin/env sh
# Auto-generated by `commandments install-sync-hook`.
# Runs `commandments sync --after=previous` when composer.lock changed in
# the incoming merge (a team-mate upgraded a dependency).

changed_files="$(git diff-tree -r --name-only ORIG_HEAD HEAD 2>/dev/null)"

if printf '%s\n' "$changed_files" | grep -qx 'composer\.lock'; then
    if [ -x vendor/bin/commandments ]; then
        vendor/bin/commandments sync --after=previous || true
    fi
fi

HOOK;
    }
}
