<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Console;

use JesseGall\CodeCommandments\Support\ConfigLoader;
use JesseGall\CodeCommandments\Support\ConfigMigrator;
use JesseGall\CodeCommandments\Support\Environment;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Rewrite a legacy array-style prophets list into the fluent
 * `ProphetClass::make()->severity(...)->set(...)` form. Non-destructive: it prints
 * the migrated blocks and writes a reference file; the user pastes each block over
 * their existing `'prophets' => [ ... ]`, preserving the rest of their config.
 */
class MigrateConfigConsoleCommand extends Command
{
    protected function configure(): void
    {
        $this
            ->setName('migrate-config')
            ->setDescription('Convert a legacy array-style prophets list to the fluent ProphetClass::make()->… form')
            ->addOption('config', 'c', InputOption::VALUE_REQUIRED, 'Path to commandments.php config file')
            ->addOption('out', null, InputOption::VALUE_REQUIRED, 'Where to write the reference file (default: alongside the config)');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $basePath = getcwd() ?: '.';
        Environment::setBasePath($basePath);

        $configPath = ConfigLoader::resolve($input->getOption('config'), $basePath);

        if ($configPath === null) {
            $output->writeln('<error>No configuration file found.</error> Run "commandments init" first.');

            return Command::FAILURE;
        }

        $config = ConfigLoader::load($configPath);
        $scrolls = $config['scrolls'] ?? [];

        if (! is_array($scrolls) || $scrolls === []) {
            $output->writeln('<comment>No scrolls found in the config — nothing to migrate.</comment>');

            return Command::SUCCESS;
        }

        $migrator = new ConfigMigrator;
        $rendered = [];

        foreach ($scrolls as $name => $scroll) {
            $prophets = is_array($scroll) ? ($scroll['prophets'] ?? []) : [];

            if (! is_array($prophets) || $prophets === []) {
                continue;
            }

            $block = "        '{$name}' => [\n            // … keep this scroll's path / extensions / exclude / thresholds …\n            'prophets' => [\n"
                . $migrator->migrateProphets($prophets)
                . "\n            ],\n        ],";

            $rendered[(string) $name] = $block;
        }

        if ($rendered === []) {
            $output->writeln('<comment>No prophets lists found to migrate.</comment>');

            return Command::SUCCESS;
        }

        $reference = "<?php\n\n"
            . "// Fluent migration of your prophets lists (generated by `commandments migrate-config`).\n"
            . "// Add `use JesseGall\\CodeCommandments\\Results\\Severity;` near the top of your\n"
            . "// commandments.php, then paste each scroll's `'prophets' => [ … ]` over the old one.\n"
            . "// `->set('key', value)` is the generic setter; swap in a prophet's typed method\n"
            . "// (e.g. `->minCallers(10)`, `->initializersOnly()`) where one exists.\n\n"
            . "// 'scrolls' => [\n"
            . implode("\n\n", $rendered)
            . "\n// ],\n";

        $out = $input->getOption('out') ?: dirname($configPath) . '/commandments.migrated.php';
        file_put_contents($out, $reference);

        foreach ($rendered as $name => $block) {
            $output->writeln("<info>── scroll: {$name} ──</info>");
            $output->writeln($block);
            $output->writeln('');
        }

        $output->writeln("<info>Reference written to</info> {$out}");
        $output->writeln('Add <comment>use JesseGall\\CodeCommandments\\Results\\Severity;</comment> and paste each block over your existing prophets list.');

        return Command::SUCCESS;
    }
}
