<?php

declare(strict_types=1);

namespace JesseGall\CodeCommandments\Support\Resolvers\Transforms;

/**
 * Maps a matched value before a resolver factory sees it. Pass any callable to
 * `Predicate::transform()`; extend this for a reusable, named transform with a
 * static factory (e.g. `StripPrefix::of('list:')`).
 *
 * The type parameter TOut is what the transform yields — it flows through
 * `Predicate::transform()` so PHPStan types the factory you pass to `then()`.
 *
 * Generated by code-commandments — safe to edit.
 *
 * @code-commandments-generated
 *
 * @template-covariant TOut
 */
abstract class Transform
{

    /**
     * @return TOut
     */
    abstract public function __invoke(mixed $value): mixed;

}
